/deploy <package>: do not assume that `req.body.comment.body` is a string
Apparently it is not, as I got this response for
https://github.com/git-for-windows/build-extra/pull/455#issuecomment-1362063606:

	TypeError: Cannot read properties of undefined (reading 'startsWith')

Let's just do the same as for the `/mention` command: use regular
expressions. If we use only greedy expressions, we should not run into
the same issues as caused the scary StackOverflow outage described in
https://stackstatus.tumblr.com/post/147710624694/outage-postmortem-july-20-2016.

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>