guess details better for GPG updates
Our current guessing is so bad that /open pr fails with
> ERROR: PKGBUILD not found or is not a file
this is because we guess the package name "gpg" when we need "gnupg" instead.
Additionally, the version number we guess is prefixed with "gnupg-" which is
undesirable. Update our heuristic to produce usefull details for GPG updates.

Signed-off-by: Matthias Aßhauer <mha1993@live.de>